id: PCB66DAFA
initial_creation_type: ocr
source_metadata:
  volumes:
    dc875772579047ba99f8f72a1bdbdbfa:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: འབྲེལ་པ་བརྟག་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1198
      volume_number: 97
